spring:
  application:
    name: akkordWeb

  datasource:
    url: ${SPRING_APPLICATION_NAME}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${SPRING_JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: true
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET:your_default_secret_key_here_please_change_in_production}
  expiration: 86400000 # 24 hours in milliseconds

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
  show-actuator: false
  packages-to-scan: com.akkor.hotel.controller

application:
  security:
    jwt:
      secret-key: ${SPRING_JWT_SECRET_TOKEN}
      expiration: 86400000 # 24 heures en millisecondes
