# AKKORD HOTEL GITHUB WORKFLOW
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# In this workflow I try to install my all dependencies on Ubuntu-latest VM
# Install my testing workflow
# and generate package
# documentation.

name: AKKORD CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  schedule:
  - cron: "0 5 * * 1-5"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: SetUp Node
      uses: actions/setup-node@v4
      with:
        node_version: '22.14.x'
   # - name: Build with Maven
     # run: mvn -B package --file pom.xml
    
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
