name: AKKORD backend CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: SetUp Node
      uses: actions/setup-node@v4
      with:
        node_version: '22.14.x'
    - name: Run the Maven verify phase
      run: mvn -clean install
  test:
    runs-on: unbuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Test Report
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
          name: SpringBoot Report               
          path: target/site/serenity/
    
  deploy:
     runs-on: ubuntu-lastest
     needs: test

     steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - name: Deploy the solution
       run: echo "Succesfully deploy, thanks!!!!"
